### PR TITLE
tests/d: fix compat w/ >=dub-1.41.0

### LINKED ISSUE #15719: CI: 17 dub and meson project fails in OpenSUSE container
The CI image builder is failing for OpenSUSE: https://github.com/mesonbuild/meson/actions/runs/24584013531/job/71888918845?pr=15711#step:5:643

In a Fedora rawhide container, it fails the same way with latest dmd+dub:
```shell
$ curl -fsS https://dlang.org/install.sh | bash -s dmd
$ ./run_single_test.py "./test cases/d/17 dub and meson project"/
WARNING: No include directory found parsing "gcc -xobjective-c -E -v -" output

host machine compilers

c      : [gcc]      cc (gcc 16.0.1 "cc (GCC) 16.0.1 20260321 (Red Hat 16.0.1-0)")
cpp    : [not found]
cs     : [not found]
cuda   : [not found]
cython : [not found]
d      : [dmd]      dmd (dmd 2.112.0 "DMD64 D Compiler v2.112.0")
fortran: [not found]
java   : [not found]
linearasm: [not found]
masm   : [not found]
nasm   : [not found]
objc   : [not found]
objcpp : [not found]
rust   : [not found]
swift  : [not found]
vala   : [not found]

tools

ninja  : /usr/bin/ninja (1.13.2)
cmake  : not found
hotdoc : not found

FAIL: d: 17 dub and meson project
[...]
    raise DependencyException('Multiple version requirements are not solvable for raw dub dependencies')
mesonbuild.dependencies.base.DependencyException: Dependency lookup for urld with method 'dub' failed: Multiple version requirements are not solvable for raw dub dependencies
```

If I downgrade to dub-1.40.0, it works (fails as expected because I haven't got `urld` in this container):
```shell
$ curl -fsS https://dlang.org/install.sh | bash -s dub-1.41.0
$ source ~/dlang/dub-1.40.0/activate
$ ./run_single_test.py "./test cases/d/17 dub and meson project"/
[...]
Found DUB: /root/dlang/dub-1.40.0/dub (version 1.40.0)
Determining dependency 'urld' with DUB executable '/root/dlang/dub-1.40.0/dub'
Searching in DUB cache for compatible liburld.a
ERROR: urld@3.0.0 not found
You may try the following command to install the necessary DUB libraries:
dub build --deep --arch=x86_64 --compiler=gdc --build=debug
Run-time dependency urld for d found: NO  (tried dub)

test cases/d/17 dub and meson project/meson.build:14:7: ERROR: Dependency "urld" not found (tried dub)
```

### PR DESCRIPTION
**Pull request by thesamesam**
dub-1.41.0 starts to reject invalid dub.json (5cf450f5fd2f62a3d60207ba4bdeb9599783cd0f) which hits us in multi-configuration:
```
(dmd-2.112.0)[root multi-configuration]# dub
Error /tmp/meson/test cases/d/17 dub and meson project/multi-configuration/dub.json(3:21): configurations: Expected to be sequence (array), but is a mapping
```

Correct it based on the docs at https://dub.pm/dub-guide/recipe/#configurations

Closes: https://github.com/mesonbuild/meson/issues/15719

### CODE REVIEW

File: ci/ciimage/opensuse/install.sh [hunk 1]
```diff
@@ -1,5 +1,6 @@
 #!/bin/bash
 
+
```
Comment (bonzini) [inline ci/ciimage/opensuse/install.sh]: Unnecessary empty line.

File: docs/markdown/Release-notes-for-0.64.0.md [hunk 2]
```diff
@@ -94,7 +94,7 @@ method.
 ## BSD support for the `jni` dependency
 
 This system dependency now supports all BSD systems that Meson currently
-supports, including FreeBSD, NetBSD, OpenBSD, and DragonflyBSD.
+supports, including FreeBSD, NetBSD, OpenBSD, and DragonFlyBSD.
```
Comment (bonzini) [inline docs/markdown/Release-notes-for-0.64.0.md]: Missing space before BSD

**Review by bonzini — COMMENTED** [review]
Two aesthetic comments only from me

File: docs/markdown/Release-notes-for-0.64.0.md (hunk 2 above)
Comment (thesamesam) [reply docs/markdown/Release-notes-for-0.64.0.md]: Whoops, thanks.

File: ci/ciimage/opensuse/install.sh (hunk 1 above)
Comment (thesamesam) [reply ci/ciimage/opensuse/install.sh]: Will drop that commit on merge, just needed it to trigger the container image rebuild workflows.
